# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-02 23:47
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rss_feeds', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default=b'')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_title', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=False)),
                ('last_read_date', models.DateTimeField(default=datetime.datetime(2016, 11, 2, 23, 47, 0, 274621))),
                ('mark_read_date', models.DateTimeField(default=datetime.datetime(2016, 11, 2, 23, 47, 0, 274621))),
                ('unread_count_neutral', models.IntegerField(default=0)),
                ('unread_count_positive', models.IntegerField(default=0)),
                ('unread_count_negative', models.IntegerField(default=0)),
                ('unread_count_updated', models.DateTimeField(default=datetime.datetime.now)),
                ('oldest_unread_story_date', models.DateTimeField(default=datetime.datetime.now)),
                ('needs_unread_recalc', models.BooleanField(default=False)),
                ('feed_opens', models.IntegerField(default=0)),
                ('is_trained', models.BooleanField(default=False)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='rss_feeds.Feed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscriptionFolders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folders', models.TextField(default=b'[]')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'folder',
                'verbose_name_plural': 'folders',
            },
        ),
        migrations.AlterUniqueTogether(
            name='usersubscription',
            unique_together=set([('user', 'feed')]),
        ),
    ]
