# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-02 23:47
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import timezone_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField()),
                ('payment_amount', models.IntegerField()),
                ('payment_provider', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_premium', models.BooleanField(default=False)),
                ('premium_expire', models.DateTimeField(blank=True, null=True)),
                ('send_emails', models.BooleanField(default=True)),
                ('preferences', models.TextField(default=b'{}')),
                ('view_settings', models.TextField(default=b'{}')),
                ('collapsed_folders', models.TextField(default=b'[]')),
                ('feed_pane_size', models.IntegerField(default=242)),
                ('tutorial_finished', models.BooleanField(default=False)),
                ('hide_getting_started', models.NullBooleanField(default=False)),
                ('has_setup_feeds', models.NullBooleanField(default=False)),
                ('has_found_friends', models.NullBooleanField(default=False)),
                ('has_trained_intelligence', models.NullBooleanField(default=False)),
                ('last_seen_on', models.DateTimeField(default=datetime.datetime.now)),
                ('last_seen_ip', models.CharField(blank=True, max_length=50, null=True)),
                ('dashboard_date', models.DateTimeField(default=datetime.datetime.now)),
                ('timezone', timezone_field.fields.TimeZoneField(default=b'America/New_York')),
                ('secret_token', models.CharField(blank=True, max_length=12, null=True)),
                ('stripe_4_digits', models.CharField(blank=True, max_length=4, null=True)),
                ('stripe_id', models.CharField(blank=True, max_length=24, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
